#!/bin/bash
set -e

cd $(dirname $0)/..

# load .env
if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | grep "FSESL_PASSWORD" | xargs)
fi

CONTAINER_ID=$(docker ps | grep freeswitch | awk '{print $1}')
docker exec $CONTAINER_ID fs_cli -H freeswitch -p "$FSESL_PASSWORD"
