apiVersion: v1
kind: Service
metadata:
  name: bbb-pads-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: bbb-pads
  clusterIP: 10.120.0.18
