apiVersion: v1
kind: Service
metadata:
  name: bbb-web-service
spec:
  type: ClusterIP
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: bbb-web
  clusterIP: 10.120.0.2
