apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-persistentvolume2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tmp/key.pem"
