apiVersion: v1
kind: PersistentVolume
metadata:
  name: coturn-persistentvolume1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/coturn/entrypoint.sh"
