apiVersion: v1
kind: Service
metadata:
  name: etherpad-service
spec:
  type: ClusterIP
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: etherpad
  clusterIP: 10.120.0.4
