apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: etherpad
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etherpad
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/bbb-net: "true"
        io.kompose.service: etherpad
        app: etherpad
    spec:
      containers:
        - env:
            - name: ETHERPAD_API_KEY
              value: 1LeU6Do5DkpC8NWt8q4iyBCePO81PRIB6Rv1UvcA
          image: asia-east1-docker.pkg.dev/mplus-video-conference/mplus/bbb-k8s-etherpad:1.8.18-2
          ports:
          - containerPort: 6379
          name: etherpad
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
      restartPolicy: Always
status: {}
