apiVersion: v1
kind: Service
metadata:
  name: freeswitch-service
spec:
  type: ClusterIP
  ports:
  - name: fsesl
    port: 8021
    protocol: TCP
    targetPort: 8021
  selector:
    app: freeswitch
  clusterIP: 10.120.0.7
