apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeswitch-persistentvolume0
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/freeswitch/conf/sip_profiles"
