apiVersion: v1
kind: Service
metadata:
  name: fsesl-akka-service
spec:
  type: ClusterIP
  ports:
  - port: 8021
    protocol: TCP
    targetPort: 8021
  selector:
    app: fsesl-akka
  clusterIP: 10.120.0.14
