apiVersion: v1
kind: PersistentVolume
metadata:
  name: https-proxy-persistentvolume1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/https/site-ipv4only.conf"
