apiVersion: v1
kind: Service
metadata:
  name: jodconverter-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jodconverter
  clusterIP: 10.120.0.20
