apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kurento
  name: kurento
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kurento
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: kurento
    spec:
      hostNetwork: true
      containers:
        - image: kurento/kurento-media-server:6.17
          name: kurento
          ports:
          - containerPort: 8888
          resources: {}
          volumeMounts:
            - mountPath: /var/kurento
              name: vol-kurento
      restartPolicy: Always
      volumes:
        - name: vol-kurento
          persistentVolumeClaim:
            claimName: vol-kurento
status: {}
