apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: asia-east1-docker.pkg.dev/mplus-video-conference/mplus/bbb-k8s-nginx:v2.5.5-230117
          name: nginx
          ports:
            - containerPort: 7443
          resources: {}
          volumeMounts:
            - mountPath: /var/bigbluebutton
              name: bigbluebutton
            - mountPath: /html5-static
              name: html5-static
              readOnly: true
            - mountPath: /www/default.pdf
              name: nginx-claim2
      restartPolicy: Always
      volumes:
        - name: bigbluebutton
          persistentVolumeClaim:
            claimName: bigbluebutton
        - name: html5-static
          persistentVolumeClaim:
            claimName: html5-static
            readOnly: true
        - name: nginx-claim2
          persistentVolumeClaim:
            claimName: nginx-claim2
status: {}
