apiVersion: v1
kind: Service
metadata:
  name: webrtc-sfu-service
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 3008
    protocol: TCP
    targetPort: 3008
  selector:
    app: webrtc-sfu
  clusterIP: 10.120.0.11
